[project]
name = "08-data-agent-mcp-chainlit"
version = "0.1.0"
requires-python = ">=3.11, <3.14"
dependencies = [
    "chainlit==2.6.8",
    "dapr-agents",
    "psycopg[binary]==3.2.9",
    "python-dotenv>=1.2.1",
    "websockets>=12.0",
]

[tool.uv.sources]
dapr-agents = { workspace = true }
