[project]
name = "02-llm-call-hugging-face"
version = "0.1.0"
requires-python = ">=3.11, <3.14"
dependencies = [
    "dapr-agents",
    "python-dotenv>=1.2.1",
]

[tool.uv.sources]
dapr-agents = { workspace = true }
