version: 2
updates:
  # Git
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  # Python
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  # Docker compose
  - package-ecosystem: "docker-compose"
    directory: "quickstarts/05-multi-agent-workflow-k8s/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]