apiVersion: apps/v1
kind: Deployment
metadata:
  name: gandalf
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gandalf
  template:
    metadata:
      annotations:
        dapr.io/app-id: gandalf
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "59191"
      labels:
        app: gandalf
    spec:
      containers:
        - name: gandalf
          image: localhost:5001/gandalf:latest
          imagePullPolicy: Always
          env:
            - name: APP_ID
              value: gandalf
            - name: DAPR_METRICS_PORT
              value: "59191"
          envFrom:
            - secretRef:
                name: openai-secrets
