apiVersion: apps/v1
kind: Deployment
metadata:
  name: legolas
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legolas
  template:
    metadata:
      annotations:
        dapr.io/app-id: legolas
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "59192"
      labels:
        app: legolas
    spec:
      containers:
        - name: legolas
          image: localhost:5001/legolas:latest
          imagePullPolicy: Always
          env:
            - name: APP_ID
              value: legolas
            - name: DAPR_METRICS_PORT
              value: "59192"
          envFrom:
            - secretRef:
                name: openai-secrets
