[project]
name = "02-llm-call-open-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.14"
dependencies = [
    "dapr-agents",
    "python-dotenv>=1.2.1",
    "tiktoken==0.9.0",
]

[tool.uv.sources]
dapr-agents = { workspace = true }
